### ISSUE TITLE
mmseqs2.sh in conda recipe

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/hypro#14]
@CoffeeMA2go Is it possible to avoid that the user has to point to the exact path of ``mmseqs2.sh``? 

```bash
hypro.py -i run/prokka/testrun.gff -o run/hypro -d uniprotkb -t pathotoconda/envs/hypro/bin/mmseqs2.sh -m full
``` 

It would be great if, from the conda env, the user can simply call

```bash
hypro.py -i run/prokka/testrun.gff -o run/hypro -d uniprotkb -t mmseqs2.sh -m full
```

**Comment by marlt** [comment]
This was a problem of argument checking, the script is executable as mmseqs2.sh without absolute path specification. I adapted the check_args function, working now with the 'which mmseqs2.sh' bash function
