### ISSUE TITLE
Result DB not updated by mmseqs search

### ISSUE THREAD

**Issue by marlt** [hoelzer-lab/hypro#21]
This seems like a weird behavior:
I added the parameters -a/-p/-e to the hypro.py script and hand over those to the mmseqs2 script. The handover to mmseqs2 is correct (can be seen in the mmseqs search parameter in stdout while execution).
However, the results remain unfiltered.
When building the DB from the scratch, including download and creating the output hyprot folder, the parameters apply. 
I finally noticed that the results-db files are not updated once they were built. I do not no of any parameter to update those - do you?
Hence, removing the results-db results in mmseqs2 building the results all over and the parameter apply.

**Comment by marlt** [comment]
I put the example output here. If you find the time @hoelzer, please try to reproduce those results. 
[mmseqs_output.txt](https://github.com/hoelzer-lab/hypro/files/4517746/mmseqs_output.txt)
I could fix this by asking if the results db was already build - if yes, remove al files belonging to them and run mmseqs search with the chosen parameters

**Comment by hoelzer** [comment]
Ah okay, so that means that the results of mmseqs2 depend on the parameter setup that was used to build the database? And when the database exists it is not overwritten with a new parameter setup?

**Comment by hoelzer** [comment]
maybe what you can do is add the parameter information `-a/-p/-e` to the dir name where the mmseqs2 database is stored. let's say it is then named something like

```
mmseqs2_db_a10_p90_e0.0001
```

Now, when the script is executed again you can check if the provided parameters still fit the dir name and in that case do not calculate the mmseqs2 index again. 

When there is a change, you can simply build the db again and add the corresponding folder, e.g.

```
mmseqs2_db_a20_p60_e0.0001
```

Does this make sense? Is this easy doable?

**Comment by marlt** [comment]
There are three DBs with mmseqs2: query DB, target DB and results DB. The first two do not play a role in this (although it was my first guess - i tried it out - but the parameters didnt work although i rebuild querydb and targetdb). mmseqs search seems to save the results in the results db and that is not correctly overwritten as far as i understand it, yes.

**Comment by marlt** [comment]
So one results db per parameter settings - yes that shall be no huge problem

**Comment by marlt** [comment]
The results from the run would otherwise not be reproducable. 
Ha, looks like this is a good raw-data-destruction prevention

**Comment by hoelzer** [comment]
ah okay... hm... but then maybe there is something like a `--force` parameter for mmseqs2 to simply overwrite the results DB each time you execute the tool? This would solve the problem in the easiest way I guess. 

Or assign a time stamp to the result db folder each time the script is executed :)

**Comment by marlt** [comment]
What about an individual name for every parameter combination?
And shall we report this to the mmseqs2 people?

**Comment by marlt** [comment]
mmh, mmseqs2 does not create the resultsdb in a subdirectory of ./resultsdb. Instead, all db files are generated in this directory. This can get confusing very easily

**Comment by marlt** [comment]
we can save all tsvs with unique codes in the name like "mmseqs_out_a0.0_p0.6.e0.0001.tsv" and just keep the latest resultsdb i suggest?

**Comment by hoelzer** [comment]
ah ok, sounds good to me! So you save the final output file with the parameter codes (nice) and then for each run the resultsdb is deleted so that we make sure that things are recalculated? fine for me
