### ISSUE TITLE
Turn into nextflow workflow

### ISSUE THREAD

**Issue by phiweger** [hoelzer-lab/hypro#28]
Super useful tool, but would be even better wrapped in a wf manager :)

**Comment by hoelzer** [comment]
true ;) and should be relatively easy to do. I will keep it in mind. 

And in this context hypro could also integrate a script to check for fragmented gene annotations and mark/merge them:
* https://github.com/tseemann/prokka/issues/502#issuecomment-691300245

**Comment by hoelzer** [comment]
@phiweger it's now a nf wf ;) Still a simple workflow but could be more easily extended now to larger databases for a more detailed functional annotation initially provided by prokka.
