### ISSUE TITLE
mmseq2 database download and indexing

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/hypro#3]
I think at the moment the script does not check if the database already exists? So it downloads and builds the index each time of script execution, right @CoffeeMA2go ?

**Comment by marlt** [comment]
Yes, only checking for now is by gzip to overwrite an existing fasta of same name.

**Comment by marlt** [comment]
I suggest to check, if all index files are present in DIR; if not, the index is asumed to be corrupted and thus it will be build. This is rather time consuming because of many if clauses. Do you have another way in mind?

**Comment by hoelzer** [comment]
I suggest the following:

1) add a parameter to directly give the script the path to a mmseq2-formated database
In that case, this db is simply used and nothing is downloaded. This will also make testing easier

2) if no db is provided, check if you find the database and if mmseq2 index files exist for the db that you are currently using as a default, if not: download and build. 

Also, I do not get your point about time-consuming if clauses? You mean it is time-consuming to check if index files exist? Just check one file if multiple exist for a mmseq2 db and if this one file does not exist, assume that the db is corrupted/ not complete and build the index again.

**Comment by hoelzer** [comment]
@CoffeeMA2go I think this works now? When I execute the script on the same output folder the database is not downloaded again. 

So the above 2. is done, right? 

How about the above 1.?

**Comment by hoelzer** [comment]
@CoffeeMA2go see [1.] above. Do you think this can be easily integrated? 

background: if the user already has a mmseq2 db ready he might wants to use this.

**Comment by marlt** [comment]
Mmh, I think this shall be done easily. since there is already a method to check if a mmseq2 db is valid, I would do the following:
1. Add a parameter to specify a PATH where a mmseq2 db was deposited.
2. Check, if the mmseq2 db is valid, otherwise exit with a warning message, to check the db or to choose the automated db download by the tool.

**Comment by hoelzer** [comment]
great sounds good to me! @CoffeeMA2go

**Comment by marlt** [comment]
I introduced a parameter -c which requires a PATH. here, a database of the type defined under '-d' is expected. If there was no found, prokkaX will build the db in here. Readme is updated. Also for using prokka version 1.14.5

**Comment by hoelzer** [comment]
great, thx!
