### ISSUE TITLE
Nextflow: summary output

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/hypro#32]
I remember that the "stand-alone" hypro version outputted some stats about the number of hypothetical proteins and how many were improved by the tool. This might be still an terminal output of the `update_prokka.py` we just have to catch this into a file to also publish it as a final result.

**Comment by EvaFriederike** [comment]
The terminal output and log information of each process are already covered by the respective .command.log files that are generated by nextflow. They are renamed by the process name and all published in nextflow-run-infos/ . Would you rather have just one log file that covers all steps?

**Comment by hoelzer** [comment]
Yeah, that's already cool to have all the logs for investigation if necessary. Would I meant is having some output/file that directly tells the user how many hypothetical proteins were assigned a function. 

I remember we had such a terminal print output in the original HyPro version and likely the script still writes this information - now in the `.command.log` file probably. If so, it would be nice if we can just extract that information and write it e.g. in a separate `hypro-summary.txt` so it's easy to check after a run what happend and how many hypos became an additional annotation.

**Comment by EvaFriederike** [comment]
The most relevant hypro output is now stored as _hypro_summary.txt_ in the result directory of the current run and is additionally printed in the terminal as an outro with workflow completion.
