### ISSUE TITLE
Provide full and spare mode on hyprot selection

### ISSUE THREAD

**Issue by marlt** [hoelzer-lab/hypro#5]
This issue comes from the observation, that prokka provides hyprots with no information at all and hyprots that were found to be similar to an entry in a database but were not annotated further for certain reasons. These entry differ in structure which the hyprot extraction of prokkaX is currently based on. So for now it just extracts the "fully unknown" hyprots and shall be improved with a 'full' mode, that covers all hyprots with the homology search.

**Comment by hoelzer** [comment]
@CoffeeMA2go ah ok. I was not aware of two different "versions" of hyprots reported by Prokka. 

I agree, the default should be to simply annotate the "fully unknown" hyprots with an option to annotate "all" hyprots reported by prokka

**Comment by marlt** [comment]
shall be achieved by latest update!
