### ISSUE TITLE
Is it possible that the extension just finds another hypothetical protein?

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/hypro#8]
In the example gff output: 

```
NZCP015840.1Chaydiaaiaa08	Prodigal:2.6	CDS	135854	136471	.	+	0	ID=PKGMDCHJ_00120;inference=mmseqs2 uniprotkb;locus_tag=PKGMDCHJ_00120;product=Q9Z6P9;product=hypothetical protein;aln_info_query=PKGMDCHJ_00120;aln_info_target=Q9Z6P9;aln_info_pident=0.6629999999999999;aln_info_alnlen=612;aln_info_mismatch=67;aln_info_gapopen=0;aln_info_qlen=618;aln_info_qstart=1;aln_info_qend=612;aln_info_tstart=1;aln_info_tend=201;aln_info_evalue=1.438e-81;aln_info_bits=271;aln_info_symbol=CPn1010;aln_info_sciname=hypothetical protein
```

This seems to be a mmseq2-extended hypothetical protein. However, the extension is also just a hypothetical protein, right?

**Comment by marlt** [comment]
yes, this might be the case sometimes, because the script does not filter those hits on the uniprotkb.
I recognized this for some hyprots that were partially annotated and originated from prokka due to the uniprotkb.

**Comment by hoelzer** [comment]
Ok, but then at the end we can not imply say:

prokkaX detected 100 aditional homologies for hyprots

beacuse those 100 might also include hyprots again that are part of the uniprot db? right?

**Comment by hoelzer** [comment]
@CoffeeMA2go please see my last question

**Comment by marlt** [comment]
Yes, this is true. I could add a method to check how many of the new homolgies were found on hypothetical proteins and substract them from the total number. Sometimes however they gain a geneID but retain the product name "hypothetical protein".
I could alter the message to "x / n entries had been modified" ?

**Comment by marlt** [comment]
Thirdly I could add a second message to say sth like:
"Found x / n hypothetical proteins in the db"
"y of x hits were hypothetical proteins, again"

**Comment by hoelzer** [comment]
Yes I think this is totally fine for now. Please just implement what does not need much time for you. The 

> Found x / n hypothetical proteins in the db"
> "y of x hits were hypothetical proteins, again"\

is the most reasonable way of doing this but just altering the printed mssg is also fine.

**Comment by marlt** [comment]
Ok!

**Comment by marlt** [comment]
The program should now give a message in the way we lately discussed @hoelzer .
Please check it out :)

**Comment by hoelzer** [comment]
```
Found hits for 135 / 378 hypothetical proteins
The homology search finds 65 / 135 hypothetical proteins again.
Write extended gff:	run/prokkax/output/testrun_extended.gff
Updated 135 features in the genbank file.
```

great!
