### ISSUE TITLE
prokka gbk format not parsable with biopython SeqIO

### ISSUE THREAD

**Issue by marlt** [hoelzer-lab/hypro#9]

**Comment by marlt** [comment]
This problem can be circumvented just by self-made parsing. The format might however not be readable for downstream formats that utilize biopython

**Comment by hoelzer** [comment]
@CoffeeMA2go can you add here an example of how an entry for one gene in the GBK file looks like and how you would add the mmseq2 annotation?

**Comment by marlt** [comment]
LOCUS       NZCP015840.1Chaydiaaiaa081059583 bp   DNA  linear       21-OCT-2019
DEFINITION  Genus species strain strain.
ACCESSION

**Comment by marlt** [comment]
prokka seems to merge the LOCUS line in a strange way

**Comment by hoelzer** [comment]
weird. 

Ok, but I dont see any annotation here? Doesn't prokka put something like 'hypothetical' somewhere? 

Anyway, I think what you need to do is:

1) loop over the GBK file 
2) check in which gene context you are via the unique prokka ID (that is hopefully also part of the GBK for each gene)
3) if mmseq2 found a homology for this prokka ID, add the information to the corresponding GBK entry

**Comment by marlt** [comment]
I just copied the first 3 lines, since the error occurred in the first.
The LOCUS line is the very beginning of the file, the FEATURES foloow later and contain the info of the coding sequences including product name like "hypothetical proteins" or sth else.
In the git of prokka there are several issues adressing the lengths of contig ID (NZCP015840.1Chaydiaaiaa08) within the LOCUS line. 
Prokka utilizes the tbl2asn of the NCBI to produce genbank format files. The tbl2asn has a maximum of 16 characters for the contig ID name. if it is too long it somehow gets concatenated/merged with the length of the contig (1059583 bp) which is normally separated from the ID by a whitespace.

**Comment by marlt** [comment]
We can decide to code an own parser to modify the not entirely correct gbk file if this does not affect downstream purposes?

**Comment by hoelzer** [comment]
Ok thx for the explanation. 

I think it's not our task to fix the prokka output. Instead please focus on simply replacing the 'hypothetical protein' part with mmseq2 output in the GBK. I hope that's not too complicated to do with some own scripting.

**Comment by hoelzer** [comment]
@CoffeeMA2go is this done and can be closed?

**Comment by marlt** [comment]
Yes, this is done
